#Jekyll settings
encoding: UTF-8
permalink:	pretty
highlighter: rouge
include: ['assets/_bower_components', '.gitignore']
sass:
    style: compressed

# Site settings
title:				Shivaji Varma
email:				contact@shivajivarma.com
tagline:			'Polyglot full stack developer'
description: This site is centered around my blog, but contains lots of other content as well. You can use the links at the top, or else jump right to the various sections.
baseurl: ''
url: 				'https://shivajivarma.com' # the base hostname & protocol for your site
domain:           	shivajivarma.com
type:				website
google-analytics:	G-KNH50V85RG

# Author details
author:
  name:           'Shivaji Varma'
  location:        'Bangalore, India'
  gpage:          +ShivajivarmaDotCom
  email:          contact@shivajivarma.com
  avatar:         /profile.min.png
  fbid:           100002868559363
  gplusid:        108142170241252227550
  github:         shivajivarma
  soundcloud:     shivajivarma
  linkedin:       shivajivarma
  twitter:        shivaji_varma
  youtube:        ShivajiVarmaPusapatiVenkata

# Path to assets
css:      /assets/css
img:      /assets/img
js:       /assets/js
fonts:    /assets/fonts
docs:     /assets/docs
bower:    /assets/bower_components

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

assets:

  assets:
    - "*.png"

  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

defaults:
  -
    scope:
      path: "assets/bower_components/**/*.*"
    values:
      sitemap:         false
  -
    scope:
      path: "assets/material-kit/**/*.*"
    values:
      sitemap:         false
  -
    scope:
      path: "assets/includes/**/*.*"
    values:
      sitemap:         false


# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-spark
  - jekyll-redirect-from
