#Jekyll settings
encoding: UTF-8
permalink:	pretty
highlighter: rouge
include: ['.gitignore']
sass:
    style: compressed

# Site settings
title:				Shivaji Varma
email:				contact@shivajivarma.com
tagline:			'Polyglot full stack developer'
description: This site is centered around my blog, but contains lots of other content as well. You can use the links at the top, or else jump right to the various sections.
baseurl: ''
url: 				'https://shivajivarma.com' # the base hostname & protocol for your site
domain:           	shivajivarma.com
type:				website
google-analytics:	G-KNH50V85RG
goatuiJs: https://cdn.jsdelivr.net/npm/@goatui/components@1.8.0/dist/goatui/goatui.esm.js
goatuiCss: https://cdn.jsdelivr.net/npm/@goatui/components@1.8.0/dist/goatui/assets/styles/theme.css

# Author details
author:
  name:           'Shivaji Varma'
  location:        'Hyderabad, India'
  email:          contact@shivajivarma.com
  avatar:         /profile.min.png
  github:         shivajivarma
  soundcloud:     shivajivarma
  linkedin:       shivajivarma
  twitter:        shivaji_varma
  youtube:        ShivajiVarmaPusapatiVenkata

# Path to assets
css:      /assets/css
img:      /assets/img
js:       /assets/js
fonts:    /assets/fonts
docs:     /assets/docs

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

assets:

  assets:
    - "*.png"
    - "*.css"

  sources:
    - _assets/css
    - _assets/js
    - _assets/img

defaults:
  -
    scope:
      path: "assets/includes/**/*.*"
    values:
      sitemap:         false


# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-spark
  - jekyll-redirect-from
