# Dependencies
pygments:         true
server:           true
auto:             on
exclude:
- README.md
- LICENSE.md
- build.bat
- archive
- Thumbs.db
- deploy.bat

# Permalinks
permalink:        pretty

# Setup
title:            'Shivaji Varma'
tagline:          'Developer, designer and dreamer'
description:      'Developer by day, designer by noon and dreamer by night'
url:              http://shivajivarma.com
domain:           shivajivarma.com
baseurl: 
type:             website

# Author
author:
  name:           'Shivaji Varma'
  gpage:          +ShivajivarmaDotCom
  email:          contact@shivajivarma.com
  avatar:         http://shivajivarma.com/assets/images/author-bw.jpg
  fbid:           100002868559363
  gplusid:        116941078508380009042

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/shivajivarma/shivajivarma.github.io

# Google analytics track id
google_analytics: "UA-42422649-1"

# Path to assets
stylesheets:      /assets/stylesheets
images:           /assets/images
javascripts:      /assets/javascripts
fonts:            /assets/fonts