auto: true
permalink: pretty
pygments: true
server: true
exclude:
- README.md

# Name of site
name: Sample Jekyll Blog

# Site description
description: Developer by day, designer by noon and dreamer by night

# Author name
author: Shivaji Varma

# Author image
author_image: http://shivajivarma.com/assets/images/author.jpg

# Author email
author_email: contact@shivajivarma.com

site_type: website

# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

# Domain name
url: http://shivajivarma.com

domain: shivajivarma.com

# Time zone
timezone: Asia/Kolkata

# Google analytics track id
google_analytics: "UA-42422649-1"

# Path to CSS files
stylesheets: /assets/stylesheets

# Path to image files
images: /assets/images

# Path to javascript files
javascripts: /assets/javascripts