# Dependencies
pygments:         true
server:           true
exclude:
- README.md

# Permalinks
permalink:        pretty

# Setup
title:            'Shivaji Varma'
tagline:          'Developer by day, designer by noon and dreamer by night'
description:      'Developer by day, designer by noon and dreamer by night'
url:              http://shivajivarma.com
domain:           shivajivarma.com
baseurl: 
type:             website

# Author
author:
  name:           'Shivaji Varma'
  url:            https://plus.google.com/116941078508380009042
  email:          contact@shivajivarma.com
  avatar:         http://shivajivarma.com/assets/images/author.jpg
  fbid:           100002868559363

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/shivajivarma/shivajivarma.github.io

# Google analytics track id
google_analytics: "UA-42422649-1"

# Path to assets
stylesheets:      /assets/stylesheets
images:           /assets/images
javascripts:      /assets/javascripts
fonts:            /assets/fonts