auto: true
permalink: /blog/:year/:month/:day/:title
pygments: true
server: true
exclude:
- README.md
- Rakefile

# Name of site
name: Sample Jekyll Blog

# Site description
description: This is a sample Jekyll Blog.

# Author name
author: "shivaji varma"

# Author email
author_email: you@example.com


# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

# Domain name
url: http://shivajivarma.com/

# Time zone
timezone: Asia/Kolkata
